### ISSUE TITLE
All hosts on one line causes resolution trouble, especially on Windows

### ISSUE THREAD

**Issue by rfay** [lextoumbourou/goodhosts#11]
Could goodhosts use a single line per host in the hosts file? Or a limit of how many hosts get added to a single line? The long lines seem to cause occasional trouble with name resolution macOS, and more than 10 hosts per line seems to be completely nonfunctional at least in some WIndows versions, see https://superuser.com/questions/932112/is-there-a-maxium-number-of-hostname-aliases-per-line-in-a-windows-hosts-file

Spurred by request in https://github.com/drud/ddev/issues/948

**Comment by outdoorsman** [comment]
I'm definitely seconding this @rfay. I'm using Windows 10 and it took a while to debug my environment to figure out the limits on a certain number of hosts in one line. To me it seems this is more than a feature, as it actually breaks functionality without accounting for this.

**Comment by micdah** [comment]
As far as I can tell the limit is 9 aliases per line in Windows - so yeah would definitely be excellent to get this fixed, or have some way to work around it, at least. Say, disabling the behaviour where it bundles aliases for same IP together (_could even just be disabled by default on Windows_)

**Comment by rfay** [comment]
I did take an extensive look at this, but. this project is very, very hostsfle-line focused., so it's nearly a rewrite to fix.  It assumes that the first line where it finds the IP is the only one.

**Comment by micdah** [comment]
I just took a closer look at the code, and found a way to add this behaviour. I needed only to re-write the `Add` method a bit. I have introduced the `appendToLine` constant which is setup in `const.go` (_`true` for Linux/Darwin systems_) and `const_windows.go` (_`false` for Windows_).

```
// Add an entry to the hosts file.
func (h *Hosts) Add(ip string, hosts ...string) error {
	if net.ParseIP(ip) == nil {
		return errors.New(fmt.Sprintf("%q is an invalid IP address.", ip))
	}

	if appendToLine {
		position := h.getIpPosition(ip)
		if position == -1 {
			newLine := NewHostsLine(buildRawLine(ip, hosts))
			// Ip line is not in file, so we just append our new line.
			h.Lines = append(h.Lines, newLine)
		} else {
			// Otherwise, we replace the line in the correct position
			newHosts := h.Lines[position].Hosts
			for _, addHost := range hosts {
				if itemInSlice(addHost, newHosts) {
					continue
				}

				newHosts = append(newHosts, addHost)
			}
			newLine := NewHostsLine(buildRawLine(ip, newHosts))
			h.Lines[position] = newLine
		}
	} else {
		// Otherwise we append the line to the end
		newLine := NewHostsLine(buildRawLine(ip, hosts))
		h.Lines = append(h.Lines, newLine)
	}

	return nil
}
```

I simply always append to the end when adding a host, when not `appendToLine` is enabled.

This has a few quirks:

- It will allow you to add `host -> ip` mappings which already exists, whereas existing logic ensures not to add duplicates (_could be mitigated in the new code, I just didn't need it for our use case_).
- It will allow you to add more than the 9 maximum hosts for a single line, if you invoke `Add` with more than 9 hosts, so the client code need to not add multiple hosts at once, or only add up to 9 at a time. Could also easily be fixed by iterating the `hosts` slice when not in append mode.

**Comment by rfay** [comment]
Would love to see your PR. Probably your fork and your PR :) , but we can hope for a response from the maintainer, this issue queue hasn't had much in recent years. This has been a solidly reliable library for us on all platforms though, and much appreciated for that.

**Comment by micdah** [comment]
I took another look into it and put a bit more effort into the implementation, accommodating the two quirks I mentioned earlier.

https://github.com/lextoumbourou/goodhosts/pull/13

**Comment by lextoumbourou** [comment]
I'm sorry I haven't had time in the recent years to give this repo much love (and I'm sorry for spamming you all with the same message on multiple issues). Please refer to the new org for this repo [here](https://github.com/goodhosts)
