### ISSUE TITLE
no close method

### ISSUE THREAD

**Issue by cocotyty** [lextoumbourou/goodhosts#9]
so ,if my program run on windows and  flush hosts changes.
other program can not read hosts file any more until my program exit.

**Comment by lobre** [comment]
Hello,

I know this is an old issue but this happers on Windows because there is a missing `file.Close()` in the `Flush` method.

You can see my fork [here](https://github.com/lobre/goodhosts).

And precisely this [commit](https://github.com/lobre/goodhosts/commit/f1568f269913106586c5c5f2b228e18254246502)

Loric

**Comment by lextoumbourou** [comment]
I'm sorry I haven't had time in the recent years to give this repo much love (and I'm sorry for spamming you all with the same message on multiple issues). Please refer to the new org for this repo [here](https://github.com/goodhosts)
